### ISSUE TITLE
не надо вызывать toString()

### ISSUE THREAD

**Issue by dzhivushko** [panasik/payment_system#11]
https://github.com/panasik/payment_system/blob/334563a1afb2beac8a76022aa7d13172aaf41759/dao/src/main/java/com/itacademy/jd2/vp/payment_system/dao/impl/UserDaoImpl.java#L42

это ошибка. не надо вызывать toString(). этот метод сам вызовется перед печатью строки. сигнатура метода позволяет передать Object. и потом внутри оно дернет у него toString().
ключевой момент в том, что он может не понадобиться если уровень логирования ниже debug.
а ты дергаешь этот метод влюбом случае. а он может быть тяжелым

**Comment by panasik** [comment]
понял. спасибо
